version: 0.0
os: linux
files:
  - source: /artifacts/
    destination: /home/ec2-user/koreanbabo/
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
  - location: scripts/after_install.sh
    runas: ec2-user
  ApplicationStart:
  - location: scripts/su_ec2.sh
    runas: ec2-user
  - location: scripts/start_server.sh
    runas: ec2-user
