version: 0.0
os: linux
files:
  - source: /artifacts/
    destination: /home/ec2-user/koreanbabo/
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ec2-user/koreanbabo/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
  - location: scripts/su_ec2.sh
  - location: scripts/start_server.sh
