version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/koreanbabo/
	overwrite: yes
file_exists_behavior: OVERWRITE
	
hooks:
  AfterInstall:
    - location: after_install.sh
	  runas: ec2-user

  ApplicationStart:
    - location: start_server.sh
	  runas: ec2-user
