version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - node -v
      - npm -v
  pre_build:
    commands:
      - echo Entered the install phase...
      - sudo npm install
  build:
    commands:
      - sudo npm build
  post_build:
    commands:
      - mkdir -p artifacts
      - find . -type f ! -path "./node_modules/*" -print0 | cpio -0pd artifacts/
artifacts:
  files:
    - "**/*"
  overwrite: true
